module.exports.fakeUsers = [
  {
    googleId: '7652496',
    isProfileCreated: 'true',
    interest: 'Korean',
    firstName: 'Corry',
    lastName: 'Ursulette',
    email: 'undefined.undefined@gmail.com',
    isATutor: 'true',
    'tutor.language': 'Korean',
    'tutor.about': '',
    'tutor.skills': '',
    'tutor.photo': 'https://placehold.co/350',
  },
  {
    googleId: '9648743',
    isProfileCreated: 'true',
    interest: 'French',
    firstName: 'Lila',
    lastName: 'Gladstone',
    email: 'undefined.undefined@gmail.com',
    isATutor: 'false',
    'tutor.language': 'Spanish',
    'tutor.about': '',
    'tutor.skills': '',
    'tutor.photo': 'https://placehold.co/350',
  },
  {
    googleId: '9648743',
    isProfileCreated: 'true',
    interest: 'French',
    firstName: 'Lila',
    lastName: 'Gladstone',
    email: 'undefined.undefined@gmail.com',
    isATutor: 'false',
    'tutor.language': 'Spanish',
    'tutor.about': '',
    'tutor.skills': '',
    'tutor.photo': 'https://placehold.co/350',
  },
  {
    googleId: '5278408',
    isProfileCreated: 'true',
    interest: 'Korean',
    firstName: 'Judy',
    lastName: 'Glovsky',
    email: 'undefined.undefined@gmail.com',
    isATutor: 'false',
    'tutor.language': 'Mandarin',
    'tutor.about': '',
    'tutor.skills': '',
    'tutor.photo': 'https://placehold.co/350',
  },
  {
    googleId: '5066074',
    isProfileCreated: 'true',
    interest: 'Japanese',
    firstName: 'Cristabel',
    lastName: 'Sperling',
    email: 'undefined.undefined@gmail.com',
    isATutor: 'true',
    'tutor.language': 'Japanese',
    'tutor.about': '',
    'tutor.skills': '',
    'tutor.photo': 'https://placehold.co/350',
  },
  {
    googleId: '5066074',
    isProfileCreated: 'true',
    interest: 'Japanese',
    firstName: 'Cristabel',
    lastName: 'Sperling',
    email: 'undefined.undefined@gmail.com',
    isATutor: 'true',
    'tutor.language': 'Japanese',
    'tutor.about': '',
    'tutor.skills': '',
    'tutor.photo': 'https://placehold.co/350',
  },
  {
    googleId: '8407701',
    isProfileCreated: 'true',
    interest: 'English',
    firstName: 'Nonnah',
    lastName: 'Nahum',
    email: 'undefined.undefined@gmail.com',
    isATutor: 'true',
    'tutor.language': 'Japanese',
    'tutor.about': '',
    'tutor.skills': '',
    'tutor.photo': 'https://placehold.co/350',
  },
  {
    googleId: '1120809',
    isProfileCreated: 'true',
    interest: 'Korean',
    firstName: 'Winifred',
    lastName: 'Donoghue',
    email: 'undefined.undefined@gmail.com',
    isATutor: 'true',
    'tutor.language': 'Japanese',
    'tutor.about': '',
    'tutor.skills': '',
    'tutor.photo': 'https://placehold.co/350',
  },
  {
    googleId: '9467917',
    isProfileCreated: 'true',
    interest: 'Korean',
    firstName: 'Donnie',
    lastName: 'Ellord',
    email: 'undefined.undefined@gmail.com',
    isATutor: 'false',
    'tutor.language': 'French',
    'tutor.about': '',
    'tutor.skills': '',
    'tutor.photo': 'https://placehold.co/350',
  },
  {
    googleId: '3611981',
    isProfileCreated: 'true',
    interest: 'English',
    firstName: 'Roz',
    lastName: 'Ahab',
    email: 'undefined.undefined@gmail.com',
    isATutor: 'true',
    'tutor.language': 'English',
    'tutor.about': '',
    'tutor.skills': '',
    'tutor.photo': 'https://placehold.co/350',
  },
  {
    googleId: '5172128',
    isProfileCreated: 'true',
    interest: 'French',
    firstName: 'Amii',
    lastName: 'Nore',
    email: 'undefined.undefined@gmail.com',
    isATutor: 'true',
    'tutor.language': 'Japanese',
    'tutor.about': '',
    'tutor.skills': '',
    'tutor.photo': 'https://placehold.co/350',
  },
];

// {
//   "googldId": random(1000000, 10000000),
//   "isProfileCreated": randomBool(),
//   "interest": choice('Korean', 'English', 'French', 'Japanese', 'Spanish', 'Mandarin'),
//   "firstName": firstname(),
//   "lastName": lastname(),
//   "email": function () {
//     	return this.firstname + '.' + this.lastname + '@gmail.com';
//   },
//   "isATutor": randomBool(),
//   "tutor.language": choice('Korean', 'English',
//                            'French', 'Japanese', 'Spanish', 'Mandarin'),
//       	"tutor.about": "",
//     	"tutor.skills": "",
//   		"tutor.photo": "https://placehold.co/350"

// }
