module.exports.fakeUsers = [
  {
    firstName: 'Padilla ',
    lastName: 'Mccarty',
    interest: 'Japanese',
    email: 'padillamccarty@elita.com',
    googleId: 23909805408629,
    isATutor: true,
    isProfileCreated: true,
    'tutor.language': 'English',
    'tutor.photo': 'https://picsum.photos/id/123/300',
    'tutor.about': 'In ipsum velit amet nulla veniam eiusmod incididunt consectetur ea anim. Eiusmod amet laboris Lorem laborum velit et ex exercitation nulla id voluptate. Est eu nulla exercitation anim cupidatat ullamco cillum labore reprehenderit consequat cillum veniam. Velit nulla nisi amet occaecat elit excepteur minim consectetur amet proident laborum eiusmod. Cillum in ex sunt mollit culpa. Nulla aute magna elit veniam Lorem.\r\n',
    'tutor.skills': 'Et incididunt ipsum qui laboris aute aliqua aliquip nulla proident nulla do et duis. Eiusmod sint quis occaecat elit enim anim sint. Lorem anim ad sit quis aute. Lorem occaecat qui officia officia cillum anim cillum qui in aliqua velit nulla commodo aliquip. Aliqua deserunt veniam minim aute irure et sit sunt incididunt elit proident laborum anim ipsum.\r\n',
  },
  {
    firstName: 'Whitney ',
    lastName: 'Henry',
    interest: 'French',
    email: 'whitneyhenry@elita.com',
    googleId: 60995359162592,
    isATutor: true,
    isProfileCreated: true,
    'tutor.language': 'Mandarin',
    'tutor.photo': 'https://picsum.photos/id/141/300',
    'tutor.about': 'Laborum occaecat aliquip sint non cupidatat ut aliqua non. Dolore minim aute dolore ea Lorem consectetur quis veniam exercitation cupidatat labore cillum deserunt. Culpa nulla eiusmod Lorem laborum incididunt velit.\r\n',
    'tutor.skills': 'Dolore nulla eu elit cupidatat dolor ut ullamco velit duis qui proident minim excepteur. Reprehenderit ad est nulla aliquip incididunt fugiat. Officia cillum ad anim ex magna laborum ea cupidatat ut aute. Minim adipisicing qui ea nisi aute aliqua quis enim quis cupidatat irure irure. Aliqua nostrud voluptate id non ea eu pariatur ipsum. Elit esse quis ad exercitation eu nisi deserunt dolor commodo laborum. Fugiat duis laboris minim duis culpa nulla proident id.\r\n',
  },
  {
    firstName: 'Andrews ',
    lastName: 'Farmer',
    interest: 'Mandarin',
    email: 'andrewsfarmer@elita.com',
    googleId: 38667773208157,
    isATutor: true,
    isProfileCreated: true,
    'tutor.language': 'Mandarin',
    'tutor.photo': 'https://picsum.photos/id/31/300',
    'tutor.about': 'Fugiat sunt esse cillum nostrud nisi deserunt ad pariatur cillum. Veniam tempor ex dolor incididunt ut. Aliqua id ipsum do et voluptate Lorem dolore duis eu velit irure est veniam ut. Nostrud velit laborum laborum consectetur exercitation. Non velit enim deserunt cillum tempor velit elit et labore ipsum laborum dolore. Velit excepteur ea enim sit qui enim ullamco commodo ut fugiat elit amet tempor ipsum. Consequat laboris deserunt eu exercitation tempor sunt.\r\n',
    'tutor.skills': 'Incididunt eu laborum cillum non et Lorem aute adipisicing. Sit enim sunt voluptate irure elit do aute qui. Deserunt anim in ea nostrud cillum. Enim officia dolore aute aliquip ut sunt ipsum aliqua laborum. Minim elit eiusmod non eiusmod incididunt fugiat exercitation eu in exercitation. Velit cupidatat do incididunt eu labore magna commodo veniam commodo cillum occaecat officia.\r\n',
  },
  {
    firstName: 'Jenna ',
    lastName: 'Frederick',
    interest: 'Japanese',
    email: 'jennafrederick@elita.com',
    googleId: 81926135025606,
    isATutor: true,
    isProfileCreated: true,
    'tutor.language': 'Japanese',
    'tutor.photo': 'https://picsum.photos/id/153/300',
    'tutor.about': 'Eu occaecat esse minim irure voluptate. Cillum cillum nulla irure nulla commodo enim consectetur. Occaecat officia ullamco adipisicing consequat.\r\n',
    'tutor.skills': 'Do labore eu anim quis ad. Voluptate elit cillum eiusmod ex esse labore eu occaecat culpa non nisi quis officia laboris. Ea laboris deserunt aliqua fugiat mollit. Reprehenderit irure reprehenderit incididunt consequat Lorem eiusmod aliquip Lorem excepteur tempor. Non labore velit pariatur occaecat non est id et ea voluptate ut occaecat Lorem. Eiusmod commodo Lorem reprehenderit qui eu mollit sint irure ullamco esse exercitation consectetur in.\r\n',
  },
  {
    firstName: 'Paulette ',
    lastName: 'Eaton',
    interest: 'Mandarin',
    email: 'pauletteeaton@elita.com',
    googleId: 28623275845936,
    isATutor: true,
    isProfileCreated: true,
    'tutor.language': 'English',
    'tutor.photo': 'https://picsum.photos/id/27/300',
    'tutor.about':
      'Dolor nisi aliqua nisi ut incididunt id adipisicing do nisi voluptate sunt aute veniam esse. Pariatur officia minim proident do ea nostrud ullamco est minim duis consequat nulla laboris. Amet do Lorem non voluptate ut reprehenderit est eu Lorem irure commodo proident esse. Ex excepteur ullamco in in. Ea consequat consectetur magna consequat. Duis occaecat magna eu cillum Lorem sunt Lorem tempor pariatur officia proident. Exercitation minim culpa voluptate nulla Lorem laboris Lorem magna.\r\n',
    'tutor.skills': 'Reprehenderit eiusmod qui aliqua fugiat ex exercitation esse ullamco fugiat. Elit eu cupidatat sint eu non ullamco adipisicing officia. Incididunt voluptate qui pariatur aute elit laboris labore adipisicing nulla irure ex. Exercitation sit ipsum incididunt veniam dolore ex magna et. Consectetur exercitation duis tempor et id ad nostrud.\r\n',
  },
  {
    firstName: 'Johnson ',
    lastName: 'Sharp',
    interest: 'Japanese',
    email: 'johnsonsharp@elita.com',
    googleId: 98408123817767,
    isATutor: true,
    isProfileCreated: true,
    'tutor.language': 'Spanish',
    'tutor.photo': 'https://picsum.photos/id/117/300',
    'tutor.about': 'Eu non et do cillum sint laborum. Pariatur dolore amet et fugiat ut ullamco quis nisi occaecat commodo. Magna voluptate nostrud Lorem Lorem qui ad nisi elit anim voluptate velit voluptate. Eiusmod reprehenderit duis eu id velit qui consequat mollit officia officia anim eiusmod ullamco. Incididunt Lorem magna nostrud incididunt. Tempor veniam excepteur sit minim ut dolore nisi non reprehenderit sint. Nulla dolor enim ad occaecat duis magna elit est minim do.\r\n',
    'tutor.skills': 'Eiusmod elit sint reprehenderit excepteur irure aliquip magna ex magna exercitation commodo. Velit velit ex adipisicing eiusmod adipisicing ad. Qui consectetur irure ipsum officia velit cupidatat ipsum consequat reprehenderit dolor.\r\n',
  },
  {
    firstName: 'Ratliff ',
    lastName: 'Woods',
    interest: 'Japanese',
    email: 'ratliffwoods@elita.com',
    googleId: 25249986847689,
    isATutor: true,
    isProfileCreated: true,
    'tutor.language': 'French',
    'tutor.photo': 'https://picsum.photos/id/33/300',
    'tutor.about': 'Ipsum consectetur id labore esse ea sint et in et ipsum fugiat sit ea laboris. Magna reprehenderit velit id ea deserunt labore nostrud voluptate irure amet. Irure laborum ea commodo et labore irure exercitation anim officia cillum occaecat. Aute irure voluptate voluptate et labore tempor adipisicing sunt voluptate. Aliquip enim pariatur incididunt voluptate eu commodo cupidatat. Non incididunt eiusmod deserunt sint cillum tempor consequat occaecat incididunt id aute.\r\n',
    'tutor.skills': 'Eiusmod sint sint enim duis excepteur dolore. Aliquip aliquip tempor aute excepteur. Ea irure officia pariatur nulla dolor culpa elit eu nostrud. Dolor occaecat minim laborum cillum magna nostrud commodo ea cillum incididunt consequat duis esse dolor. Veniam ex occaecat id dolore aute dolore eu in eiusmod dolore dolore ex eu laborum.\r\n',
  },
  {
    firstName: 'Rosario ',
    lastName: 'Briggs',
    interest: 'Spanish',
    email: 'rosariobriggs@elita.com',
    googleId: 29344774925425,
    isATutor: true,
    isProfileCreated: true,
    'tutor.language': 'Mandarin',
    'tutor.photo': 'https://picsum.photos/id/175/300',
    'tutor.about': 'Dolore aliquip qui voluptate pariatur consequat ullamco ex. Lorem commodo nostrud nulla nostrud elit non aliquip culpa sunt sunt proident cillum adipisicing cillum. Eiusmod laboris occaecat adipisicing magna proident proident sunt aliquip proident. Sit in aliqua dolor culpa nisi excepteur nostrud sunt deserunt cupidatat laborum magna.\r\n',
    'tutor.skills': 'Sunt magna amet reprehenderit voluptate reprehenderit qui ipsum nisi nisi. Commodo reprehenderit sit consectetur est qui sint pariatur culpa cupidatat enim et. Fugiat ad fugiat nulla voluptate laboris labore cillum laboris quis reprehenderit tempor.\r\n',
  },
  {
    firstName: 'Celina ',
    lastName: 'Buchanan',
    interest: 'Japanese',
    email: 'celinabuchanan@elita.com',
    googleId: 16725279055222,
    isATutor: true,
    isProfileCreated: true,
    'tutor.language': 'French',
    'tutor.photo': 'https://picsum.photos/id/15/300',
    'tutor.about': 'Laboris fugiat do enim pariatur. Proident sit voluptate consectetur Lorem aliqua sunt dolore id irure enim tempor id. Elit velit nisi qui amet incididunt. Ad consectetur amet sint dolor occaecat consectetur. Laborum deserunt irure quis velit pariatur velit esse nostrud officia.\r\n',
    'tutor.skills': 'Aute pariatur veniam exercitation tempor. Dolor ex minim commodo aliquip anim consectetur tempor officia. Do consequat excepteur cupidatat laboris exercitation cupidatat laboris nisi consectetur ullamco nostrud nulla. Occaecat elit et cupidatat sint fugiat et reprehenderit. Enim aliqua proident id dolor non fugiat qui laboris culpa excepteur dolore.\r\n',
  },
  {
    firstName: 'Diane ',
    lastName: 'Ramirez',
    interest: 'Japanese',
    email: 'dianeramirez@elita.com',
    googleId: 78065172635212,
    isATutor: true,
    isProfileCreated: true,
    'tutor.language': 'Japanese',
    'tutor.photo': 'https://picsum.photos/id/9/300',
    'tutor.about': 'Sunt laborum laboris eu incididunt nisi sit Lorem tempor aliquip aute aute pariatur est. Pariatur amet in adipisicing dolor irure mollit sint nisi. Ex ullamco pariatur aliqua reprehenderit Lorem non. Irure et irure enim velit ad aliquip nostrud ea Lorem amet elit nostrud. Ex dolore fugiat enim pariatur nostrud sunt. Commodo in exercitation ullamco dolor laboris proident aliquip dolore sint.\r\n',
    'tutor.skills': 'Sint et exercitation voluptate nostrud ex aliquip aute cillum consectetur laborum. In voluptate id commodo in ex cupidatat. Qui et Lorem elit deserunt.\r\n',
  },
];


// JSON Generator

// [
//   '{{repeat(10)}}',
//   {
//     firstName: '{{firstName()}} ',
//     lastName: '{{surname()}}',
//     interest: function (tags) {
//       var languages = ['Korean', 'Japanese', 'English', 'French', 'Mandarin', 'Spanish'];
//       return languages[tags.integer(0, languages.length -1)];
//     },
//     email: '{{email()}}',
//     googleId: '{{integer(10000000000000, 99999999999999)}}',
//     isATutor: true,
//     isProfileCreated: true,
//     'tutor.language': function (tags) {
//       var languages = ['Korean', 'Japanese', 'English', 'French', 'Mandarin', 'Spanish'];
//       return languages[tags.integer(0, languages.length -1)];
//     },
//     'tutor.photo':'https://picsum.photos/id/{{integer(1,200)}}/300', 
//      'tutor.about': '{{lorem(1, "paragraphs")}}',
//      'tutor.skills': '{{lorem(1, "paragraphs")}}'
   
//   }
// ]